// fixtures/ui-markup-angular/src/app/dashboard/dashboard.component.ts
import { Component } from "@angular/core";

@Component({
  selector: "app-dashboard",
  templateUrl: "./dashboard.component.html",
})
export class DashboardComponent {
  title = "Angular Dashboard";
  showFilters = false;
  showUpgradeModal = false;
  rows: { name: string }[] = [];
}

<main class="dashboard-page">
  <header class="dash-bar">
    <h1>{{ title }}</h1>
    <button type="button" (click)="showFilters = true">Filters</button>
  </header>
  <aside *ngIf="showFilters" class="filters-panel">
    <h2>Filters</h2>
    <button type="button" (click)="showFilters = false">Close</button>
  </aside>
  <ul>
    <li *ngFor="let row of rows">{{ row.name }}</li>
  </ul>
  <app-upgrade-modal [isOpen]="showUpgradeModal"></app-upgrade-modal>
</main>

// fixtures/ui-markup-next/app/dashboard/page.tsx
"use client";

import { useState } from "react";
import "./page.module.css";

export default function DashboardPage() {
  const [showFilters, setShowFilters] = useState(false);
  const showUpgradeModal = false;
  return (
    <main className="dashboard-page">
      <header className="dash-bar">
        <h1>Next Dashboard</h1>
        <button type="button" onClick={() => setShowFilters(true)}>
          Filters
        </button>
      </header>
      {showFilters && (
        <aside className="filters-panel">
          <h2>Filters</h2>
          <button type="button" onClick={() => setShowFilters(false)}>
            Close
          </button>
        </aside>
      )}
      {showUpgradeModal && (
        <div className="modal-panel">
          <p>Upgrade plan</p>
        </div>
      )}
    </main>
  );
}
